### ISSUE TITLE
Stress dices not shown when Foundry is in Spanish language

### ISSUE THREAD

**Issue by Eldebor** [pwatson100/alienrpg#69] opened 2021-03-31 15:53 UTC
If Foundry is set up to spanish language, yellow dices are not shown. Failures of successes are not counted either.
With another not english languages as deustch or french it seems to work correctly.

**Comment by Eldebor** [comment] 2021-03-31 17:17
> That is very odd. I am looking into what is going on.

Yes I was very surprised when I changed to english and the behaviour was correct. Maybe is it related to the accent in the transalation of stress word (ESTRÉS) or something like that? I know that it has little sense but...

I hope I'm not wasting your time and this is not a stupid error for my part.

**Comment by pwatson100** [comment] 2021-03-31 17:17
Found it.  I was trying to test for the word 'Stress" and passing the translated text so it was seeing "Estrés" and failing the test.   I will be fixed in the next release.

**Comment by Eldebor** [comment] 2021-03-31 17:18
Great! You are doing and excellent work, by the way.

**Comment by NeV3rKilL** [comment] 2021-04-10 12:04
I the issue is in the line 247 from the YZEDiceRoller.js

      if (dType != 'Stress') {


The dType with the translation is "Estrés" this should be an issue for all the languages.

The condition should use game.i18n.localize('ALIENRPG.Stress') function.

A part from that, that same function has some English lines hardcoded:

From line 329 to 332 of the same file:

        chatMessage += '<div style="color: goldenrod; font-weight: bold">' + col2 + '  ' + r2Dice + ' Dice</div>';
        chatMessage += '<span style="color: red">Ones: </span>';
        chatMessage += `<span>${RY1.length}</span>`;
        chatMessage += '<span style="color: #03cf03">  Sixes: </span>';


All those strings "Ones:" "Sixes:", etc. are hardcoded and a string should be created to localize them.

**Comment by pwatson100** [comment] 2021-04-10 19:25
Thank you.  I have fixed this and it will be n the next release.  The issue was when I called the function I was using this: 
      buildChat(mr, r1Dice, game.i18n.localize('ALIENRPG.Stress'));
Where I should have been using this:
      buildChat(mr, r1Dice, 'Stress');
I have also localized Ones and Sixes.

**Comment by pwatson100** [comment] 2021-04-10 19:26
Fixed in version 1.3.5

**Closed by pwatson100** 2021-04-10 19:26 UTC
Labels: bug
