### ISSUE TITLE
Alien RPG : Chariot of the Gods - Various Issues

### ISSUE THREAD

**Issue by GittaNaba2021** [pwatson100/alienrpg#53] opened 2021-03-13 13:17 UTC
Hello,

Here is a list of issues I've got when playing Chariot of the Gods with Foundry VTT (I activated only the Starter Set):

- A "Skill-Stunts" list with empty description is located in "Items Discovery" panel. It is not needed unless you didn't buy any of the official modules.
- "Heavy Machinery" stunts are currently unavailable, replaced by "Close Combat" stunts.
- Watatsumi DV-303 Bolt Gun  and Cutting Torch are missing their +2 Heavy Machinery bonus when used as a tool (under "Alien RPG Equipment" category under "Items Directory" folder).
- With Cutting Torch having it's own Power Supply, I'm not sure how the Power Roll button works when players are wearing more than one object with Power at the same time (like a motion tracker and a Cutting Torch). It seems to add Power from all items, when each should be managed separately.
- Also, Power Roll is not available for tools used as weapons.
- On Cronus Deck B, the door inside Corporate Suit, leading to EEV, should be locked and hidden instead of opened and revealed.

Thanks for the help ! I'll continue to report bugs as I go further into the game.

**Comment by pwatson100** [comment] 2021-03-13 14:11
_A "Skill-Stunts" list with empty description is located in "Items Discovery" panel. It is not needed unless you didn't buy any of the official modules._
I did not overwrite or remove the skill-stunt entries from the base system as people may have put their own information.  The way the system works is they have to exist for the code to work.  When the Core Rules or starter set are installed the system checks them and if they have the default text it looks at a language file for the correct text.   

_"Heavy Machinery" stunts are currently unavailable, replaced by "Close Combat" stunts._
I corrected the Language file in the Core Rules but forgot to do the same in the Starter Set.  This will be corrected in the next update (2.0.3)

_Watatsumi DV-303 Bolt Gun and Cutting Torch are missing their +2 Heavy Machinery bonus when used as a tool (under "Alien RPG Equipment" category under "Items Directory" folder)._
I will correct these errors and they will be in the 2.0.3 update.

_With Cutting Torch having it's own Power Supply, I'm not sure how the Power Roll button works when players are wearing more than one object with Power at the same time (like a motion tracker and a Cutting Torch). It seems to add Power from all items, when each should be managed separately._
How power in the system works as a whole is a bit contrived (as per the rules) as I explain in the MO/TH/ER instructions.  It does total the power from all "Active" items in the Power box on the General tab.  I am trying to think of a better way of implementing that in the system.  The problem is that per the rules for an item with one power you still roll all the available power dice.  The system does not know which item the player is actually using when they press the power button.  I am looking at alternatives.

_Also, Power Roll is not available for tools used as weapons._
For Equipment that could be used as a weapon I created a separate entry in the weapons folder that would not have the bonus when used as a tool.   That said I have tested and as long as the "Tool" is "Active" I can see the power number updating and the supply roll works (for me).

_On Cronus Deck B, the door inside Corporate Suit, leading to EEV, should be locked and hidden instead of opened and revealed._
I missed that and will correct it in the next update.  


Thank you for your feedback.  It is much appreciated.

**Comment by pwatson100** [comment] 2021-03-13 14:33
I just realised why I did not add the +2 to to the Watatsumi DV-303 Bolt Gun and Cutting Torch.  
Reading the text it says:
"When used as a tool, the XXXXXX gives a +2 modification to Heavy Machinery in **relevant situations.**" 
The system would give the +2 to any rolls against Heavy Machinery regardless of weather the tool was actually being used when it's activated.   I have not been able to work out a way to only give the bonus when the tool was being used in the right situation.

**Comment by GittaNaba2021** [comment] 2021-03-14 12:37
Hello,

I can suggest a workaround then :
- If I ask for a standard Heavy Machinery roll, players click on the corresponding skill. No modifiers expected, unless I explicitly call for it (in-game, right-click on the skill).
- If I ask for a Heavy Machinery skill using the appropriate tool, players click on the tool name inside their inventory, within "Active Items". The roll will be automatically modified with the appropriate modifiers (e.g, +2 for Cutting Torch).
- If I ask for an attack roll using a tool, players click on the tool name inside their inventory, within "Active Weapons". 

Currently only option 2 doesn't work for me - when clicking on the button, nothing happens. If you could fix that, that would solve this issue - revelant situation would mean "have the right item, equip it, and have the GM ask you to roll with it."

**Comment by pwatson100** [comment] 2021-03-17 09:39
I have added Option 2 to my project list of enhancements.  I agree it would be useful, I just need to work out how it would work for all items and not just those with bonuses.  It's a little like trying to automate Talents.  There are a lot of permutations/conditions when using a talent which make automating them extremely complex. 

Thank you for your feedback.  I am going to close this issue now.

**Closed by pwatson100** 2021-03-17 09:39 UTC
